version: '3.8'

services:
  # Spring Boot Backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - ai-service
    networks:
      - finsense-network

  # Python AI Service
  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    networks:
      - finsense-network

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - finsense-network

networks:
  finsense-network:
    driver: bridge 