server:
  port: 8080

spring:
  application:
    name: finsense-backend
  
  datasource:
    url: jdbc:postgresql://db.wlrwvjovdejhiexddymj.supabase.co:5432/postgres
    username: postgres
    password: ${SUPABASE_DB_PASSWORD:your_supabase_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:MqIGvQewNC+9TnYL/FVPdWMK3QhcJJDG7qx4ykd2xoois8MAHz2iPr7jNJwtoOLTHRhhf7QPTbScTjvl0h70lQ==}

# AI Service Configuration
ai-service:
  base-url: http://localhost:8001
  timeout: 30000

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging
logging:
  level:
    com.finsense: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG 